version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
    - ./:/usr/src/app
    - /usr/src/app/node_modules
    container_name: todo-api
    ports:
      - "3000:3000"
    environment:
      # - MONGO_URI=mongodb+srv://triminhnguyen2098:KVmmcAkiww4U7NDv@todo-app.rleya.mongodb.net/?retryWrites=true&w=majority&appName=todo-app
      - MONGO_URI=mongodb://mongo:27017/todos
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: todo-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  nginx:
    image: nginx
    container_name: todo-nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app

volumes:
  mongo_data:
